package com.jpa3d.export

import kotlin.test.Test
import kotlin.test.assertContains
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * DdlExporter 단위 테스트.
 *
 * 각 테스트는 ExportModel 을 in-memory 로 빌드 → DdlExporter 실행 → SQL substring 검증.
 * 헤더 코멘트의 `generatedAt` 만 시간 의존이라 본문 substring 위주로만 어서트한다.
 */
class DdlExporterTest {

    // ===================================================================================
    // 헬퍼 — 데이터 클래스 기본값이 많아 매번 풀어쓰면 노이즈가 큼.
    // ===================================================================================

    private fun col(
        name: String,
        type: String = "java.lang.String",
        pk: Boolean = false,
        nullable: Boolean = true,
        unique: Boolean = false,
        indexed: Boolean = false,
        fk: String? = null,
        length: Int? = null,
        generated: String? = null,
        precision: Int? = null,
        scale: Int? = null,
        lob: Boolean = false,
        sequenceName: String? = null,
        columnName: String? = null,
        columnNameExplicit: Boolean = false
    ) = ExportColumn(
        name = name,
        columnName = columnName ?: name,
        columnNameExplicit = columnNameExplicit,
        javaType = type,
        primaryKey = pk,
        nullable = nullable,
        unique = unique,
        indexed = indexed,
        foreignKey = fk != null,
        fkTarget = fk,
        length = length,
        generatedValue = generated,
        precision = precision,
        scale = scale,
        lob = lob,
        sequenceName = sequenceName
    )

    private fun ent(
        fqn: String,
        columns: List<ExportColumn>,
        kind: String = "entity",
        tableName: String? = null,
        tableNameExplicit: Boolean = false,
        inheritance: ExportInheritance? = null,
        compositeIndexes: List<List<String>> = emptyList(),
        compositeUniques: List<List<String>> = emptyList()
    ): ExportEntity {
        val simple = fqn.substringAfterLast('.')
        return ExportEntity(
            fqn = fqn,
            name = simple,
            `package` = fqn.substringBeforeLast('.', ""),
            kind = kind,
            tableName = tableName ?: simple,
            tableNameExplicit = tableNameExplicit,
            inheritance = inheritance,
            columns = columns,
            compositeIndexes = compositeIndexes,
            compositeUniques = compositeUniques
        )
    }

    private fun extendsRel(child: String, parent: String) =
        ExportRelation(source = child, target = parent, type = "EXTENDS")

    private fun model(
        entities: List<ExportEntity>,
        relations: List<ExportRelation> = emptyList()
    ) = ExportModel(
        schemaVersion = 1,
        generatedAt = "2026-01-01T00:00:00Z",
        entities = entities,
        relations = relations
    )

    // ===================================================================================
    // 기본 타입 매핑
    // ===================================================================================

    @Test
    fun `Long PK + IDENTITY on Postgres`() {
        val m = model(listOf(ent("com.example.User", listOf(
            col("id", "java.lang.Long", pk = true, nullable = false, generated = "IDENTITY")
        ))))
        val out = DdlExporter(DdlDialect.POSTGRES).render(m)
        assertContains(out, "\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY")
        assertContains(out, "PRIMARY KEY (\"id\")")
    }

    @Test
    fun `Long PK + AUTO_INCREMENT on MySQL with backtick quoting`() {
        val m = model(listOf(ent("com.example.User", listOf(
            col("id", "java.lang.Long", pk = true, nullable = false, generated = "IDENTITY")
        ))))
        val out = DdlExporter(DdlDialect.MYSQL).render(m)
        assertContains(out, "`id` BIGINT AUTO_INCREMENT")
    }

    @Test
    fun `Long maps to NUMBER(19) on Oracle`() {
        val m = model(listOf(ent("com.example.User", listOf(
            col("id", "java.lang.Long", pk = true, nullable = false)
        ))))
        val out = DdlExporter(DdlDialect.ORACLE).render(m)
        assertContains(out, "NUMBER(19)")
    }

    @Test
    fun `LocalDateTime emits TIMESTAMP(6) on Postgres and DATETIME(6) on MySQL`() {
        val m = model(listOf(ent("com.example.E", listOf(
            col("createdAt", "java.time.LocalDateTime", columnName = "created_at")
        ))))
        assertContains(DdlExporter(DdlDialect.POSTGRES).render(m), "\"created_at\" TIMESTAMP(6)")
        assertContains(DdlExporter(DdlDialect.MYSQL).render(m), "`created_at` DATETIME(6)")
    }

    @Test
    fun `Instant emits TIMESTAMP WITH TIME ZONE on Postgres`() {
        val m = model(listOf(ent("com.example.E", listOf(
            col("at", "java.time.Instant")
        ))))
        assertContains(DdlExporter(DdlDialect.POSTGRES).render(m), "TIMESTAMP(6) WITH TIME ZONE")
    }

    @Test
    fun `UUID per dialect`() {
        val m = model(listOf(ent("com.example.E", listOf(
            col("id", "java.util.UUID", pk = true, nullable = false)
        ))))
        assertContains(DdlExporter(DdlDialect.POSTGRES).render(m), "\"id\" UUID")
        assertContains(DdlExporter(DdlDialect.H2).render(m), "\"id\" UUID")
        assertContains(DdlExporter(DdlDialect.MYSQL).render(m), "`id` CHAR(36)")
        assertContains(DdlExporter(DdlDialect.ORACLE).render(m), "\"id\" VARCHAR2(36)")
    }

    // ===================================================================================
    // PK 가드 — 비-숫자 타입에는 IDENTITY 절 미부착
    // ===================================================================================

    @Test
    fun `non-integral PK does not get IDENTITY clause`() {
        val m = model(listOf(ent("com.example.User", listOf(
            col("id", "java.util.UUID", pk = true, nullable = false, generated = "AUTO")
        ))))
        val out = DdlExporter(DdlDialect.POSTGRES).render(m)
        assertContains(out, "\"id\" UUID")
        assertFalse("GENERATED BY DEFAULT AS IDENTITY" in out, "UUID PK 에 IDENTITY 가 붙으면 안됨")
        assertFalse("AUTO_INCREMENT" in out)
    }

    @Test
    fun `String PK with GeneratedValue does not get IDENTITY`() {
        val m = model(listOf(ent("com.example.User", listOf(
            col("id", "java.lang.String", pk = true, nullable = false, generated = "AUTO", length = 36)
        ))))
        val out = DdlExporter(DdlDialect.POSTGRES).render(m)
        assertContains(out, "\"id\" VARCHAR(36)")
        assertFalse("IDENTITY" in out)
    }

    // ===================================================================================
    // FK 컬럼 타입 해소 + 복합 PK 경고
    // ===================================================================================

    @Test
    fun `FK column inherits PK type from target, not VARCHAR fallback`() {
        val user = ent("com.example.User", listOf(
            col("id", "java.lang.Long", pk = true, nullable = false)
        ))
        val order = ent("com.example.Purchase", listOf(
            col("id", "java.lang.Long", pk = true, nullable = false),
            col("user", "com.example.User", fk = "com.example.User",
                columnName = "user_id", nullable = false)
        ))
        val out = DdlExporter(DdlDialect.POSTGRES).render(model(listOf(user, order)))
        assertContains(out, "\"user_id\" BIGINT NOT NULL")
        assertFalse("\"user_id\" VARCHAR" in out, "FK 타입이 VARCHAR 로 fallback 되면 안됨")
        assertContains(out, "FOREIGN KEY (\"user_id\") REFERENCES \"user\" (\"id\")")
    }

    @Test
    fun `FK to entity with composite PK emits WARNING comment`() {
        val target = ent("com.example.OrderItem", listOf(
            col("orderId", "java.lang.Long", pk = true, nullable = false, columnName = "order_id"),
            col("productId", "java.lang.Long", pk = true, nullable = false, columnName = "product_id")
        ))
        val source = ent("com.example.Note", listOf(
            col("id", "java.lang.Long", pk = true, nullable = false),
            col("orderItem", "com.example.OrderItem", fk = "com.example.OrderItem",
                columnName = "order_item_id")
        ))
        val out = DdlExporter(DdlDialect.POSTGRES).render(model(listOf(target, source)))
        assertContains(out, "-- WARNING")
        assertContains(out, "composite PK")
    }

    // ===================================================================================
    // SINGLE_TABLE 상속 — 머지 + FK redirect (B2/B3 회귀)
    // ===================================================================================

    @Test
    fun `SINGLE_TABLE inheritance merges children into root with discriminator`() {
        val animal = ent("com.example.Animal",
            columns = listOf(
                col("id", "java.lang.Long", pk = true, nullable = false),
                col("name", "java.lang.String", length = 50)
            ),
            inheritance = ExportInheritance(strategy = "SINGLE_TABLE")
        )
        val dog = ent("com.example.Dog",
            columns = listOf(
                col("barkLoudness", "java.lang.Integer", columnName = "bark_loudness")
            ),
            inheritance = ExportInheritance(strategy = "SINGLE_TABLE", discriminatorValue = "DOG")
        )
        val out = DdlExporter(DdlDialect.POSTGRES).render(model(
            listOf(animal, dog),
            listOf(extendsRel("com.example.Dog", "com.example.Animal"))
        ))
        assertContains(out, "CREATE TABLE \"animal\"")
        assertContains(out, "\"bark_loudness\" INTEGER")
        // discriminator (snake_case ON: DTYPE → dtype)
        assertContains(out, "\"dtype\" VARCHAR(31)")
        assertFalse("CREATE TABLE \"dog\"" in out, "SINGLE_TABLE 자식은 별도 테이블을 만들면 안됨")
    }

    @Test
    fun `FK pointing at SINGLE_TABLE child is redirected to root with inherited type`() {
        val animal = ent("com.example.Animal",
            columns = listOf(col("id", "java.lang.Long", pk = true, nullable = false)),
            inheritance = ExportInheritance(strategy = "SINGLE_TABLE")
        )
        val dog = ent("com.example.Dog",
            columns = emptyList(),
            inheritance = ExportInheritance(strategy = "SINGLE_TABLE", discriminatorValue = "DOG")
        )
        val owner = ent("com.example.Owner", listOf(
            col("id", "java.lang.Long", pk = true, nullable = false),
            col("dog", "com.example.Dog", fk = "com.example.Dog", columnName = "dog_id")
        ))
        val out = DdlExporter(DdlDialect.POSTGRES).render(model(
            listOf(animal, dog, owner),
            listOf(extendsRel("com.example.Dog", "com.example.Animal"))
        ))
        // FK 컬럼 타입: 자식(Dog) 가 자체 PK 가 없어도 root(Animal) 의 BIGINT 를 빌려옴
        assertContains(out, "\"dog_id\" BIGINT")
        // FK ALTER: 자식이 아니라 root 테이블을 참조
        val fkLine = out.lines().first { it.contains("FOREIGN KEY") }
        assertContains(fkLine, "REFERENCES \"animal\"")
        assertFalse("REFERENCES \"dog\"" in fkLine, "FK 타깃이 자식 테이블을 가리키면 안됨")
    }

    // ===================================================================================
    // MappedSuperclass + TABLE_PER_CLASS — ancestor 컬럼 머지
    // ===================================================================================

    @Test
    fun `MappedSuperclass columns are merged into descendant entity table`() {
        val base = ent("com.example.Auditable",
            kind = "mappedSuperclass",
            columns = listOf(
                col("createdAt", "java.time.LocalDateTime", columnName = "created_at"),
                col("createdBy", "java.lang.String", columnName = "created_by")
            )
        )
        val entity = ent("com.example.Article", listOf(
            col("id", "java.lang.Long", pk = true, nullable = false),
            col("title", "java.lang.String", length = 200)
        ))
        val out = DdlExporter(DdlDialect.POSTGRES).render(model(
            listOf(base, entity),
            listOf(extendsRel("com.example.Article", "com.example.Auditable"))
        ))
        assertContains(out, "CREATE TABLE \"article\"")
        assertContains(out, "\"created_at\"")
        assertContains(out, "\"created_by\"")
        assertContains(out, "\"title\"")
        assertFalse("CREATE TABLE \"auditable\"" in out, "MappedSuperclass 는 자체 테이블이 없어야 함")
    }

    @Test
    fun `TABLE_PER_CLASS includes parent columns in each child table`() {
        val parent = ent("com.example.Animal",
            columns = listOf(
                col("id", "java.lang.Long", pk = true, nullable = false),
                col("name", "java.lang.String", length = 50)
            ),
            inheritance = ExportInheritance(strategy = "TABLE_PER_CLASS")
        )
        val child = ent("com.example.Dog",
            columns = listOf(col("barkLoudness", "java.lang.Integer", columnName = "bark_loudness")),
            inheritance = ExportInheritance(strategy = "TABLE_PER_CLASS")
        )
        val out = DdlExporter(DdlDialect.POSTGRES).render(model(
            listOf(parent, child),
            listOf(extendsRel("com.example.Dog", "com.example.Animal"))
        ))
        assertContains(out, "CREATE TABLE \"animal\"")
        assertContains(out, "CREATE TABLE \"dog\"")
        val dogStart = out.indexOf("CREATE TABLE \"dog\"")
        val dogEnd = out.indexOf(");", dogStart)
        val dogBlock = out.substring(dogStart, dogEnd)
        assertContains(dogBlock, "\"id\"")
        assertContains(dogBlock, "\"name\"")
        assertContains(dogBlock, "\"bark_loudness\"")
    }

    // ===================================================================================
    // @SequenceGenerator
    // ===================================================================================

    @Test
    fun `SEQUENCE strategy emits CREATE SEQUENCE and DEFAULT nextval on Postgres`() {
        val m = model(listOf(ent("com.example.User", listOf(
            col("id", "java.lang.Long", pk = true, nullable = false,
                generated = "SEQUENCE", sequenceName = "user_seq")
        ))))
        val out = DdlExporter(DdlDialect.POSTGRES).render(m)
        assertContains(out, "CREATE SEQUENCE user_seq;")
        assertContains(out, "DEFAULT nextval('user_seq')")
        // CREATE SEQUENCE 가 CREATE TABLE 보다 앞서야 함
        assertTrue(out.indexOf("CREATE SEQUENCE") < out.indexOf("CREATE TABLE"))
    }

    @Test
    fun `SEQUENCE on Oracle uses dot-nextval syntax`() {
        val m = model(listOf(ent("com.example.User", listOf(
            col("id", "java.lang.Long", pk = true, nullable = false,
                generated = "SEQUENCE", sequenceName = "user_seq")
        ))))
        val out = DdlExporter(DdlDialect.ORACLE).render(m)
        assertContains(out, "CREATE SEQUENCE user_seq;")
        assertContains(out, "DEFAULT user_seq.nextval")
    }

    @Test
    fun `SEQUENCE on MySQL falls back to AUTO_INCREMENT without CREATE SEQUENCE`() {
        val m = model(listOf(ent("com.example.User", listOf(
            col("id", "java.lang.Long", pk = true, nullable = false,
                generated = "SEQUENCE", sequenceName = "user_seq")
        ))))
        val out = DdlExporter(DdlDialect.MYSQL).render(m)
        assertFalse("CREATE SEQUENCE" in out)
        assertContains(out, "AUTO_INCREMENT")
    }

    // ===================================================================================
    // 복합 UNIQUE / INDEX (B1 회귀)
    // ===================================================================================

    @Test
    fun `composite UNIQUE emits multi-column UNIQUE INDEX`() {
        val m = model(listOf(ent("com.example.User",
            columns = listOf(
                col("id", "java.lang.Long", pk = true, nullable = false),
                col("first_name"),
                col("last_name")
            ),
            compositeUniques = listOf(listOf("first_name", "last_name"))
        )))
        val out = DdlExporter(DdlDialect.POSTGRES).render(m)
        assertContains(out, "CREATE UNIQUE INDEX")
        assertContains(out, "(\"first_name\", \"last_name\")")
    }

    @Test
    fun `composite UNIQUE with camelCase columns gets snake_case applied consistently`() {
        // B1 회귀 테스트: 분석기가 그룹 케이스를 보존하고, DdlExporter 가 snake_case 일관 적용.
        // 잘못된 동작 시 컬럼은 first_name 인데 인덱스는 firstname 을 참조해 SQL 실행 실패.
        val m = model(listOf(ent("com.example.User",
            columns = listOf(
                col("id", "java.lang.Long", pk = true, nullable = false),
                col("firstName"),
                col("lastName")
            ),
            compositeUniques = listOf(listOf("firstName", "lastName"))
        )))
        val out = DdlExporter(DdlDialect.POSTGRES, snakeCase = true).render(m)
        // 컬럼 정의도 snake_case
        assertContains(out, "\"first_name\"")
        assertContains(out, "\"last_name\"")
        // 복합 인덱스도 같은 변환 적용
        assertContains(out, "(\"first_name\", \"last_name\")")
        // 변환 누락 시 나타날 잘못된 식별자가 없어야 함
        assertFalse("\"firstname\"" in out)
    }

    @Test
    fun `composite INDEX emits multi-column INDEX`() {
        val m = model(listOf(ent("com.example.Log",
            columns = listOf(
                col("id", "java.lang.Long", pk = true, nullable = false),
                col("user_id"), col("created_at")
            ),
            compositeIndexes = listOf(listOf("user_id", "created_at"))
        )))
        val out = DdlExporter(DdlDialect.POSTGRES).render(m)
        assertContains(out, "CREATE INDEX")
        assertContains(out, "(\"user_id\", \"created_at\")")
    }

    // ===================================================================================
    // @Lob
    // ===================================================================================

    @Test
    fun `Lob String maps to TEXT on Postgres, LONGTEXT on MySQL, CLOB on Oracle`() {
        val m = model(listOf(ent("com.example.Article", listOf(
            col("id", "java.lang.Long", pk = true, nullable = false),
            col("body", "java.lang.String", lob = true)
        ))))
        assertContains(DdlExporter(DdlDialect.POSTGRES).render(m), "\"body\" TEXT")
        assertContains(DdlExporter(DdlDialect.MYSQL).render(m), "`body` LONGTEXT")
        assertContains(DdlExporter(DdlDialect.ORACLE).render(m), "\"body\" CLOB")
    }

    @Test
    fun `Lob byte array maps to BYTEA on Postgres, BLOB on MySQL`() {
        val m = model(listOf(ent("com.example.File", listOf(
            col("id", "java.lang.Long", pk = true, nullable = false),
            col("data", "byte[]", lob = true)
        ))))
        assertContains(DdlExporter(DdlDialect.POSTGRES).render(m), "\"data\" BYTEA")
        assertContains(DdlExporter(DdlDialect.MYSQL).render(m), "`data` BLOB")
    }

    // ===================================================================================
    // BigDecimal precision/scale
    // ===================================================================================

    @Test
    fun `BigDecimal uses precision and scale when specified`() {
        val m = model(listOf(ent("com.example.Invoice", listOf(
            col("id", "java.lang.Long", pk = true, nullable = false),
            col("amount", "java.math.BigDecimal", precision = 12, scale = 4)
        ))))
        assertContains(DdlExporter(DdlDialect.POSTGRES).render(m), "DECIMAL(12, 4)")
        assertContains(DdlExporter(DdlDialect.ORACLE).render(m), "NUMBER(12, 4)")
    }

    @Test
    fun `BigDecimal uses default (19, 2) when unspecified`() {
        val m = model(listOf(ent("com.example.Invoice", listOf(
            col("id", "java.lang.Long", pk = true, nullable = false),
            col("amount", "java.math.BigDecimal")
        ))))
        assertContains(DdlExporter(DdlDialect.POSTGRES).render(m), "DECIMAL(19, 2)")
    }

    // ===================================================================================
    // snake_case 옵션
    // ===================================================================================

    @Test
    fun `snake_case ON converts UserAccount to user_account`() {
        val m = model(listOf(ent("com.example.UserAccount",
            tableName = "UserAccount",
            columns = listOf(col("id", "java.lang.Long", pk = true, nullable = false))
        )))
        val out = DdlExporter(DdlDialect.POSTGRES, snakeCase = true).render(m)
        assertContains(out, "CREATE TABLE \"user_account\"")
    }

    @Test
    fun `snake_case OFF preserves original case`() {
        val m = model(listOf(ent("com.example.UserAccount",
            tableName = "UserAccount",
            columns = listOf(col("id", "java.lang.Long", pk = true, nullable = false))
        )))
        val out = DdlExporter(DdlDialect.POSTGRES, snakeCase = false).render(m)
        assertContains(out, "CREATE TABLE \"UserAccount\"")
    }

    @Test
    fun `snake_case handles acronym boundaries — HTTPRequest, userID`() {
        val m = model(listOf(ent("com.example.HTTPRequest",
            tableName = "HTTPRequest",
            columns = listOf(
                col("id", "java.lang.Long", pk = true, nullable = false, columnName = "ID"),
                col("userID", "java.lang.Long", columnName = "userID")
            )
        )))
        val out = DdlExporter(DdlDialect.POSTGRES, snakeCase = true).render(m)
        assertContains(out, "CREATE TABLE \"http_request\"")
        assertContains(out, "\"user_id\"")
    }

    @Test
    fun `explicit Table name keeps underscores verbatim — no double underscore`() {
        // 회귀: @Table(name="user_Account") 같은 명시 이름을 snake_case 에 태우면 'user__account' 가 됨.
        // 명시 물리 이름은 JPA 처럼 변환 없이 그대로 써야 한다.
        val m = model(listOf(ent("com.example.UserAccount",
            tableName = "user_Account",
            tableNameExplicit = true,
            columns = listOf(col("id", "java.lang.Long", pk = true, nullable = false))
        )))
        val out = DdlExporter(DdlDialect.POSTGRES, snakeCase = true).render(m)
        assertContains(out, "CREATE TABLE \"user_Account\"")
        assertFalse(out.contains("user__account"), "explicit @Table name must not be snake_cased")
    }

    @Test
    fun `explicit Column name keeps underscores verbatim — no double underscore`() {
        val m = model(listOf(ent("com.example.E",
            columns = listOf(
                col("id", "java.lang.Long", pk = true, nullable = false),
                col("orderRef", "java.lang.Long", columnName = "order_Ref", columnNameExplicit = true)
            )
        )))
        val out = DdlExporter(DdlDialect.POSTGRES, snakeCase = true).render(m)
        assertContains(out, "\"order_Ref\"")
        assertFalse(out.contains("order__ref"), "explicit @Column name must not be snake_cased")
    }

    @Test
    fun `derived names still get snake_case while explicit names stay verbatim`() {
        // 같은 엔티티에서 파생 컬럼은 변환, 명시 컬럼은 보존 — 두 규칙이 공존함을 보장.
        val m = model(listOf(ent("com.example.UserAccount",
            tableName = "UserAccount", // 파생(클래스명) — explicit=false
            columns = listOf(
                col("id", "java.lang.Long", pk = true, nullable = false),
                col("createdAt", "java.time.LocalDateTime"), // 파생 필드명 → created_at
                col("zipCode", "java.lang.String", columnName = "zip_Code", columnNameExplicit = true)
            )
        )))
        val out = DdlExporter(DdlDialect.POSTGRES, snakeCase = true).render(m)
        assertContains(out, "CREATE TABLE \"user_account\"") // 파생 변환
        assertContains(out, "\"created_at\"")                // 파생 변환
        assertContains(out, "\"zip_Code\"")                  // 명시 보존
        assertFalse(out.contains("zip__code"))
    }

    // ===================================================================================
    // DROP 순서 (B4 회귀)
    // ===================================================================================

    @Test
    fun `dropExisting emits DROP TABLE before DROP SEQUENCE, then CREATE SEQUENCE then CREATE TABLE`() {
        val m = model(listOf(ent("com.example.User", listOf(
            col("id", "java.lang.Long", pk = true, nullable = false,
                generated = "SEQUENCE", sequenceName = "user_seq")
        ))))
        val out = DdlExporter(DdlDialect.POSTGRES, dropExisting = true).render(m)
        val dropTable = out.indexOf("DROP TABLE")
        val dropSeq = out.indexOf("DROP SEQUENCE")
        val createSeq = out.indexOf("CREATE SEQUENCE")
        val createTable = out.indexOf("CREATE TABLE")
        assertTrue(dropTable in 0..<dropSeq, "DROP TABLE must come before DROP SEQUENCE")
        assertTrue(dropSeq < createSeq, "CREATE SEQUENCE must come after DROP SEQUENCE")
        assertTrue(createSeq < createTable, "CREATE TABLE must come after CREATE SEQUENCE")
    }

    @Test
    fun `dropExisting on Oracle wraps DROP in PL_SQL block`() {
        val m = model(listOf(ent("com.example.User", listOf(
            col("id", "java.lang.Long", pk = true, nullable = false)
        ))))
        val out = DdlExporter(DdlDialect.ORACLE, dropExisting = true).render(m)
        assertContains(out, "BEGIN")
        assertContains(out, "EXECUTE IMMEDIATE 'DROP TABLE")
        assertContains(out, "SQLCODE != -942")
    }

    // ===================================================================================
    // Oracle 30 자 식별자 제한
    // ===================================================================================

    @Test
    fun `Oracle truncates generated identifier names beyond 30 chars`() {
        val longTable = "very_long_table_name_that_exceeds_thirty_chars"
        val longCol = "very_long_column_name_too_for_testing"
        val m = model(listOf(ent("com.example.X",
            tableName = longTable,
            columns = listOf(
                col("id", "java.lang.Long", pk = true, nullable = false),
                col(longCol, "java.lang.String", indexed = true)
            )
        )))
        val out = DdlExporter(DdlDialect.ORACLE).render(m)
        val idxLine = out.lines().first { it.startsWith("CREATE INDEX") }
        val name = Regex("""CREATE INDEX "([^"]+)"""").find(idxLine)?.groupValues?.get(1)
            ?: error("could not parse index name from: $idxLine")
        assertTrue(name.length <= 30, "Oracle 식별자 '$name' (${name.length}자) 가 30자를 초과")
    }

    @Test
    fun `non-Oracle dialects do not truncate long identifiers`() {
        val longTable = "very_long_table_name_that_exceeds_thirty_chars"
        val longCol = "very_long_column_name_too_for_testing"
        val m = model(listOf(ent("com.example.X",
            tableName = longTable,
            columns = listOf(
                col("id", "java.lang.Long", pk = true, nullable = false),
                col(longCol, "java.lang.String", indexed = true)
            )
        )))
        val out = DdlExporter(DdlDialect.POSTGRES).render(m)
        val idxLine = out.lines().first { it.startsWith("CREATE INDEX") }
        val name = Regex("""CREATE INDEX "([^"]+)"""").find(idxLine)?.groupValues?.get(1)
            ?: error("could not parse")
        assertTrue(name.length > 30, "Postgres 는 truncate 하지 않아야 함")
    }

    // ===================================================================================
    // 빈 모델 / mappedSuperclass-only 모델
    // ===================================================================================

    @Test
    fun `empty entities list emits only the header`() {
        val out = DdlExporter(DdlDialect.POSTGRES).render(model(emptyList()))
        assertFalse("CREATE TABLE" in out)
        assertFalse("CREATE SEQUENCE" in out)
    }

    @Test
    fun `mappedSuperclass-only model emits nothing besides header`() {
        val m = model(listOf(ent("com.example.Base", kind = "mappedSuperclass",
            columns = listOf(col("id", "java.lang.Long", pk = true, nullable = false))
        )))
        val out = DdlExporter(DdlDialect.POSTGRES).render(m)
        assertFalse("CREATE TABLE" in out)
    }
}
