package com.jpa3d.export

import java.security.MessageDigest

/**
 * Entity 모델 → CREATE TABLE / ALTER TABLE 스크립트.
 *
 * 주요 처리:
 *   - mappedSuperclass / embeddable 은 단독 테이블이 없으므로 스킵
 *   - SINGLE_TABLE 상속: 자식 엔티티의 non-PK 컬럼을 부모 테이블에 머지, 자식 별도 CREATE TABLE 스킵
 *   - JOINED / TABLE_PER_CLASS: 각 엔티티가 자기 테이블을 가짐 — 그대로 통과 (analyzer 가 자식에 부모
 *     컬럼을 합쳐주지 않으면 부모 필드 누락 가능, 이는 모델 확장 필요)
 *   - FK 는 본문 inline 대신 ALTER TABLE 로 분리 — 순환 참조에 안전
 *   - FK 컬럼의 SQL 타입은 타깃 PK 의 javaType 을 빌려와 결정 (analyzer 는 FK 컬럼에 entity 클래스명을 박음)
 *   - 비-숫자 PK 에는 IDENTITY 절 미부착 (잘못된 SQL 생성 방지)
 *   - 다중 컬럼 UNIQUE 는 모델 한계로 단일 컬럼 인덱스로만 출력 (의미 차이는 경고 코멘트로 명시)
 *   - 복합 PK 를 가리키는 FK 는 단일 PK 만 참조 — 경고 코멘트 추가
 *   - snake_case 옵션: UserAccount → user_account (Hibernate ImplicitNamingStrategy 기본 동작과 일치)
 *   - dropExisting 옵션: 재실행 안전성 위해 머리에 DROP TABLE 추가 (Oracle 은 PL/SQL 블록)
 *   - Oracle 식별자 30자 제한: 인덱스/FK 이름이 길면 truncate + 해시 접미사
 */
class DdlExporter(
    private val dialect: DdlDialect,
    private val snakeCase: Boolean = true,
    private val dropExisting: Boolean = false
) {

    fun render(model: ExportModel): String {
        val sb = StringBuilder()
        sb.append("-- Generated by JPA 3D - dialect: ${dialect.displayName}\n")
        sb.append("-- generatedAt: ${model.generatedAt}\n")
        sb.append("-- WARNING: static-analysis approximation. Composite UNIQUE/FK, @SequenceGenerator,\n")
        sb.append("-- and some inheritance edge cases may differ from Hibernate's runtime DDL.\n\n")

        // ancestor 머지 위해 mappedSuperclass 도 포함해서 모음. emit 시엔 entity 만 출력.
        val allInheritable = model.entities.filter { it.kind == "entity" || it.kind == "mappedSuperclass" }
        val rawEntities = allInheritable.filter { it.kind == "entity" }
        if (rawEntities.isEmpty()) return sb.toString()

        // === 상속 사전 계산 — parentOf / byFqn / childToRoot 를 한 번만 구해 모든 단계에 공유 ===
        val parentOf: Map<String, String> = model.relations
            .filter { it.type == "EXTENDS" }
            .associate { it.source to it.target }
        val byFqn = allInheritable.associateBy { it.fqn }
        // SINGLE_TABLE 자식 → root 매핑. relations 에 EXTENDS 가 없으면 모든 상속 단계 스킵.
        val childToRoot: Map<String, String> =
            if (parentOf.isEmpty()) emptyMap()
            else buildSingleTableChildToRoot(allInheritable, parentOf, byFqn)

        // === FK 컬럼 정규화 — 타깃 PK 타입 + SINGLE_TABLE 자식 redirect 를 한 번에 ===
        // 결과적으로 후속 pkByFqn 룩업/FK ALTER 모두 redirect 없이 자연스럽게 동작.
        val pkByFqn: Map<String, ExportColumn> = rawEntities.mapNotNull { e ->
            e.columns.firstOrNull { it.primaryKey }?.let { e.fqn to it }
        }.toMap()
        val withFkTypes = allInheritable.map { e ->
            e.copy(columns = e.columns.map { c -> normalizeFkColumn(c, pkByFqn, childToRoot) })
        }

        // === 상속 머지 ===
        val (afterSingleTable, skippedFqns) =
            if (childToRoot.isEmpty()) withFkTypes to emptySet()
            else mergeSingleTable(withFkTypes, childToRoot, byFqn)
        val afterAncestor =
            if (parentOf.isEmpty()) afterSingleTable
            else mergeAncestorColumns(afterSingleTable, parentOf, byFqn)
        // JOINED 자식에 부모 PK 를 PK+FK 로 주입 (mergeAncestorColumns 가 JOINED 는 건드리지 않으므로 별도 단계).
        val afterJoined =
            if (parentOf.isEmpty()) afterAncestor
            else mergeJoinedPk(afterAncestor, parentOf, byFqn)

        // 실 테이블 후보: kind="entity" 이면서 SINGLE_TABLE 자식이 아닌 것.
        // referenceOnly 스텁(추출 범위 밖 FK 대상)은 FK 해석에는 쓰되 CREATE TABLE 은 만들지 않으므로
        // tableByFqn(FK 대상 룩업)에는 포함하고 emitted(실제 출력)에서는 제외한다.
        val realTables = afterJoined.filter { it.kind == "entity" && it.fqn !in skippedFqns }
        val tableByFqn = realTables.associateBy { it.fqn }
        val emitted = realTables.filter { !it.referenceOnly }

        // ManyToMany owning 관계 → 조인 테이블. 양방향이어도 owning 한쪽만 생성된다.
        val joinTables = model.relations
            .filter { it.type == "MANY_TO_MANY" && it.manyToManyOwning }
            .mapNotNull { buildJoinTableSpec(it, tableByFqn) }

        // emit 대상의 PK 컬럼이 가진 sequenceName 을 모아 CREATE SEQUENCE.
        // MySQL 은 시퀀스 미지원 — AUTO_INCREMENT 로 fallback (generationClause 에서 처리).
        val sequenceNames: List<String> = emitted.flatMap { e ->
            e.columns.filter { it.primaryKey && it.sequenceName != null }.mapNotNull { it.sequenceName }
        }.distinct()

        // === DROP 순서: TABLE → SEQUENCE — 기존 테이블이 시퀀스를 default 로 참조할 수 있어
        //     시퀀스를 먼저 dropping 하면 의존성 충돌. ===
        if (dropExisting) {
            // 조인 테이블이 owner/target 을 FK 로 참조하므로 본 테이블보다 먼저 drop.
            for (jt in joinTables) sb.append(dropTableSql(id(jt.name))).append("\n")
            for (e in emitted.reversed()) sb.append(renderDrop(e)).append("\n")
            if (dialect != DdlDialect.MYSQL && sequenceNames.isNotEmpty()) {
                for (s in sequenceNames) sb.append(renderDropSequence(s)).append("\n")
            }
            sb.append("\n")
        }

        // CREATE SEQUENCE — CREATE TABLE 보다 먼저 (DEFAULT nextval 절이 참조하므로)
        if (dialect != DdlDialect.MYSQL && sequenceNames.isNotEmpty()) {
            for (s in sequenceNames) sb.append("CREATE SEQUENCE $s;\n")
            sb.append("\n")
        }

        for (e in emitted) sb.append(renderCreateTable(e)).append("\n")
        for (jt in joinTables) sb.append(renderJoinTable(jt)).append("\n")

        // 단일 컬럼 인덱스/유니크 (column-level 플래그)
        for (e in emitted) {
            for (c in e.columns) {
                if (c.primaryKey) continue
                if (c.unique) sb.append(renderUniqueIndex(e, c)).append("\n")
                else if (c.indexed) sb.append(renderIndex(e, c)).append("\n")
            }
        }

        // 복합 인덱스/유니크 (entity-level 그룹)
        for (e in emitted) {
            for (group in e.compositeUniques) sb.append(renderCompositeIndex(e, group, unique = true)).append("\n")
            for (group in e.compositeIndexes) sb.append(renderCompositeIndex(e, group, unique = false)).append("\n")
        }

        // FK ALTER — fkTarget 은 정규화 단계에서 이미 root 로 redirect 됨
        for (e in emitted) {
            for (c in e.columns) {
                if (!c.foreignKey) continue
                val targetFqn = c.fkTarget ?: continue
                val target = tableByFqn[targetFqn] ?: continue
                sb.append(renderFk(e, c, target)).append("\n")
            }
        }
        for (jt in joinTables) sb.append(renderJoinTableFks(jt)).append("\n")

        return sb.toString()
    }

    // ===== SINGLE_TABLE 자식 → root 매핑 =====
    /**
     * EXTENDS 체인을 따라가며 SINGLE_TABLE 자식 entity 가 어느 root 에 속하는지 매핑.
     * root 자신은 결과에 포함되지 않음 (자기를 자기에게 redirect 할 일이 없으니).
     */
    private fun buildSingleTableChildToRoot(
        entities: List<ExportEntity>,
        parentOf: Map<String, String>,
        byFqn: Map<String, ExportEntity>
    ): Map<String, String> {
        val result = mutableMapOf<String, String>()
        for (e in entities) {
            if (e.inheritance?.strategy != "SINGLE_TABLE") continue
            val root = findSingleTableRoot(e.fqn, parentOf, byFqn) ?: continue
            if (root != e.fqn) result[e.fqn] = root
        }
        return result
    }

    /** [fqn] 부터 SINGLE_TABLE 부모 체인을 따라 올라가 최상위 SINGLE_TABLE 엔티티를 찾는다. */
    private fun findSingleTableRoot(
        fqn: String,
        parentOf: Map<String, String>,
        byFqn: Map<String, ExportEntity>
    ): String? {
        var cur = fqn
        var lastRoot: String? = null
        val seen = mutableSetOf<String>()
        while (cur !in seen) {
            seen.add(cur)
            val e = byFqn[cur] ?: break
            if (e.inheritance?.strategy == "SINGLE_TABLE") lastRoot = cur
            val parent = parentOf[cur] ?: break
            val parentEntity = byFqn[parent] ?: break
            // 부모도 SINGLE_TABLE 인 경우만 위로 계속 — 다른 전략 만나면 정지
            if (parentEntity.inheritance?.strategy != "SINGLE_TABLE") break
            cur = parent
        }
        return lastRoot
    }

    // ===== FK 컬럼 정규화 =====
    /**
     * FK 컬럼 한 개를 표준화:
     *   1. fkTarget 이 SINGLE_TABLE 자식이면 root FQN 으로 redirect
     *   2. 그 결과 타깃 entity 의 PK 타입을 빌려와 javaType / length 설정 (없으면 원본 유지)
     *
     * 이 한 단계로 후속 pkByFqn 룩업과 FK ALTER 가 redirect 없이 동작.
     */
    private fun normalizeFkColumn(
        c: ExportColumn,
        pkByFqn: Map<String, ExportColumn>,
        childToRoot: Map<String, String>
    ): ExportColumn {
        if (!c.foreignKey || c.fkTarget == null) return c
        val redirected = childToRoot[c.fkTarget] ?: c.fkTarget
        val targetPk = pkByFqn[redirected]
        return c.copy(
            fkTarget = redirected,
            javaType = targetPk?.javaType ?: c.javaType,
            length = targetPk?.length ?: c.length
        )
    }

    // ===== SINGLE_TABLE 상속 머지 =====
    /**
     * EXTENDS 관계를 따라 SINGLE_TABLE 부모를 찾고, 자식의 non-PK 컬럼을 부모에 합친다.
     * 부모 (root) 에는 discriminator 컬럼도 추가.
     *
     * @return (변환된 엔티티 목록, emit 에서 제외할 자식 FQN 집합)
     */
    /**
     * SINGLE_TABLE 자식 컬럼을 root 로 머지. childToRoot 가 비어 있으면 호출 전에 스킵.
     * @return (변환된 엔티티 목록, emit 에서 제외할 자식 FQN 집합 = childToRoot.keys)
     */
    private fun mergeSingleTable(
        entities: List<ExportEntity>,
        childToRoot: Map<String, String>,
        byFqn: Map<String, ExportEntity>
    ): Pair<List<ExportEntity>, Set<String>> {
        // root FQN → 자식 entity 목록 (순회 순서 유지)
        val childrenByRoot: Map<String, List<ExportEntity>> = childToRoot.entries
            .groupBy({ it.value }, { byFqn.getValue(it.key) })

        val merged = entities.map { e ->
            val children = childrenByRoot[e.fqn] ?: return@map e
            val extraCols = children.flatMap { c -> c.columns.filter { !it.primaryKey } }
            val discName = e.inheritance?.discriminatorColumn ?: DEFAULT_DISCRIMINATOR_NAME
            val hasDisc = e.columns.any { it.columnName.equals(discName, ignoreCase = true) }
            val discCol = if (hasDisc) emptyList() else listOf(defaultDiscriminatorColumn(discName))
            // 중복 컬럼명 제거 (자식들이 동일 필드명을 정의했을 때 첫 정의만 유지)
            val dedup = mutableMapOf<String, ExportColumn>()
            for (c in e.columns + discCol + extraCols) {
                dedup.putIfAbsent(c.columnName.lowercase(), c)
            }
            e.copy(columns = dedup.values.toList())
        }

        return merged to childToRoot.keys
    }

    private fun defaultDiscriminatorColumn(name: String) = ExportColumn(
        name = name,
        columnName = name,
        javaType = "java.lang.String",
        primaryKey = false,
        nullable = false,
        unique = false,
        indexed = false,
        foreignKey = false,
        length = DEFAULT_DISCRIMINATOR_LENGTH
    )

    // ===== ancestor 컬럼 머지 (MappedSuperclass + TABLE_PER_CLASS) =====
    /**
     * EXTENDS 체인을 따라 위로 올라가며 다음을 자식 테이블에 머지:
     *   - kind="mappedSuperclass" : 항상 (어떤 상속 전략이든 부모 필드가 자식 테이블에 들어감)
     *   - kind="entity" + inheritance.strategy="TABLE_PER_CLASS" : 부모 컬럼이 자식 테이블에 합쳐짐
     *
     * 그 외 (JOINED, 비-상속) ancestor 만나면 walk 종료.
     * 컬럼 순서: ancestor 가 먼저, 자식 own 컬럼이 뒤. 동일 columnName 충돌 시 자식 우선.
     */
    private fun mergeAncestorColumns(
        entities: List<ExportEntity>,
        parentOf: Map<String, String>,
        byFqn: Map<String, ExportEntity>
    ): List<ExportEntity> {
        // 자식 → 부모 → 조부모 ... 순서로 모은 뒤 reverse 해서 root ancestor 가 앞으로 오게.
        // (이전 구현은 addAll(0, ...) 로 O(n²) 였음. 단일 reverse 로 한 번에 정렬.)
        fun ancestorColumns(fqn: String): List<ExportColumn> {
            val collected = mutableListOf<ExportColumn>()
            var cur = parentOf[fqn]
            val seen = mutableSetOf<String>()
            while (cur != null && cur !in seen) {
                seen.add(cur)
                val ancestor = byFqn[cur] ?: break
                val merge = ancestor.kind == "mappedSuperclass" ||
                    (ancestor.kind == "entity" && ancestor.inheritance?.strategy == "TABLE_PER_CLASS")
                if (!merge) break
                collected += ancestor.columns
                cur = parentOf[cur]
            }
            return collected.asReversed()
        }

        return entities.map { e ->
            if (e.kind != "entity") return@map e
            val ancestors = ancestorColumns(e.fqn)
            if (ancestors.isEmpty()) return@map e
            val ownNames = e.columns.mapTo(mutableSetOf()) { it.columnName.lowercase() }
            val merged = ancestors.filter { it.columnName.lowercase() !in ownNames } + e.columns
            e.copy(columns = merged)
        }
    }

    // ===== JOINED 상속 PK 주입 =====
    /**
     * JOINED 전략 자식 테이블에 부모 PK 를 PK 이자 부모 참조 FK 로 주입한다.
     *
     * JOINED 는 부모/자식을 별도 테이블로 두되, 자식 PK 가 부모 PK 를 그대로 참조(공유)한다.
     * 자식이 자기 `@Id` 를 선언하지 않으므로 부모 PK 컬럼을 빌려와 PK+FK 로 표시.
     * 생성 전략(IDENTITY/SEQUENCE)은 값을 부모에서 받으므로 제거한다.
     * (부모 own 컬럼은 복사하지 않음 — TABLE_PER_CLASS 와 다른 점.)
     */
    private fun mergeJoinedPk(
        entities: List<ExportEntity>,
        parentOf: Map<String, String>,
        byFqn: Map<String, ExportEntity>
    ): List<ExportEntity> = entities.map { e ->
        if (e.kind != "entity" || e.inheritance?.strategy != "JOINED") return@map e
        if (e.columns.any { it.primaryKey }) return@map e // 자체 @Id 보유 시 그대로
        val parentFqn = parentOf[e.fqn] ?: return@map e
        val parentPk = findInheritedPk(parentFqn, parentOf, byFqn) ?: return@map e
        val pkCol = parentPk.copy(
            primaryKey = true,
            foreignKey = true,
            fkTarget = parentFqn,
            generatedValue = null,
            sequenceName = null
        )
        e.copy(columns = listOf(pkCol) + e.columns)
    }

    /** [fqn] 부터 EXTENDS 체인을 올라가며 PK 컬럼을 가진 첫 조상의 PK 를 찾는다. */
    private fun findInheritedPk(
        fqn: String,
        parentOf: Map<String, String>,
        byFqn: Map<String, ExportEntity>
    ): ExportColumn? {
        var cur: String? = fqn
        val seen = mutableSetOf<String>()
        while (cur != null && cur !in seen) {
            seen.add(cur)
            val e = byFqn[cur] ?: return null
            e.columns.firstOrNull { it.primaryKey }?.let { return it }
            cur = parentOf[cur]
        }
        return null
    }

    // ===== CREATE TABLE / 컬럼 =====
    private fun renderCreateTable(e: ExportEntity): String {
        val tableName = qualifiedTable(e)
        val sb = StringBuilder()
        sb.append("CREATE TABLE ").append(tableName).append(" (\n")

        val lines = mutableListOf<String>()
        for (c in e.columns) {
            // columnDefinition 은 DB 특정 raw SQL — 별도 주석 줄로 방언 비중립 경고. (콤마 영향 없는 선행 줄)
            if (c.columnDefinition != null) {
                lines += "    -- '${c.columnName}' columnDefinition is DB-specific; verify when targeting another dialect"
            }
            lines += "    " + renderColumn(c)
        }
        val pkCols = e.columns.filter { it.primaryKey }
        if (pkCols.isNotEmpty()) {
            val pkList = pkCols.joinToString(", ") { id(it.columnName) }
            lines += "    PRIMARY KEY ($pkList)"
        }
        sb.append(lines.joinToString(",\n"))
        sb.append("\n);\n")
        return sb.toString()
    }

    private fun renderColumn(c: ExportColumn): String {
        // columnDefinition 이 있으면 타입/제약 추론을 건너뛰고 raw 정의를 그대로 사용 (JPA 와 동일).
        c.columnDefinition?.let { return "${id(c.columnName)} $it" }
        val sb = StringBuilder()
        sb.append(id(c.columnName)).append(" ").append(sqlType(c))
        // 정수형 PK 일 때만 generation 절 부착 — UUID/String PK 등에 IDENTITY 가 붙는 잘못된 SQL 방지
        if (c.primaryKey && c.generatedValue != null && isIntegralType(c.javaType)) {
            generationClause(c)?.let { sb.append(" ").append(it) }
        }
        if (!c.nullable && !c.primaryKey) sb.append(" NOT NULL")
        return sb.toString()
    }

    /**
     * PK 의 generation 절 결정:
     *   - SEQUENCE + sequenceName + 방언이 시퀀스 지원 → `DEFAULT nextval(seq)` (Postgres/H2) / `DEFAULT seq.nextval` (Oracle)
     *   - 그 외 (IDENTITY/AUTO 또는 MySQL) → 기존 IDENTITY/AUTO_INCREMENT 절
     */
    private fun generationClause(c: ExportColumn): String? {
        val strat = c.generatedValue?.uppercase()
        if (strat == "SEQUENCE" && c.sequenceName != null && dialect != DdlDialect.MYSQL) {
            return when (dialect) {
                DdlDialect.POSTGRES, DdlDialect.H2 -> "DEFAULT nextval('${c.sequenceName}')"
                DdlDialect.ORACLE -> "DEFAULT ${c.sequenceName}.nextval"
                else -> null
            }
        }
        return identityClause(c.generatedValue ?: return null)
    }

    private fun isIntegralType(javaType: String): Boolean {
        val simple = javaType.substringAfterLast('.')
        return simple in INTEGRAL_TYPES
    }

    // ===== DROP =====
    private fun renderDrop(e: ExportEntity): String = dropTableSql(qualifiedTable(e))

    /** [t] 는 이미 quoting/스키마 한정된 테이블 식별자 표현. */
    private fun dropTableSql(t: String): String {
        return when (dialect) {
            DdlDialect.POSTGRES, DdlDialect.H2 -> "DROP TABLE IF EXISTS $t CASCADE;"
            DdlDialect.MYSQL -> "DROP TABLE IF EXISTS $t;"
            DdlDialect.ORACLE -> // Oracle 은 IF EXISTS 미지원 — PL/SQL 블록으로 ORA-00942 무시.
                "BEGIN\n" +
                    "  EXECUTE IMMEDIATE 'DROP TABLE $t CASCADE CONSTRAINTS';\n" +
                    "EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;\n" +
                    "END;\n/"
        }
    }

    private fun renderDropSequence(name: String): String = when (dialect) {
        DdlDialect.POSTGRES, DdlDialect.H2 -> "DROP SEQUENCE IF EXISTS $name CASCADE;"
        DdlDialect.ORACLE -> // ORA-02289 (sequence does not exist) 무시
            "BEGIN\n" +
                "  EXECUTE IMMEDIATE 'DROP SEQUENCE $name';\n" +
                "EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF;\n" +
                "END;\n/"
        DdlDialect.MYSQL -> "" // 시퀀스 미지원 — 호출 측에서 분기 처리됨
    }

    // ===== 인덱스 / FK =====
    private fun renderIndex(e: ExportEntity, c: ExportColumn): String {
        val raw = "idx_${tableNameOf(e)}_${c.columnName}".lowercase()
        val idxName = oracleLimit(raw)
        return "CREATE INDEX ${quote(idxName)} ON ${qualifiedTable(e)} (${id(c.columnName)});"
    }

    private fun renderUniqueIndex(e: ExportEntity, c: ExportColumn): String {
        val raw = "uq_${tableNameOf(e)}_${c.columnName}".lowercase()
        val idxName = oracleLimit(raw)
        return "CREATE UNIQUE INDEX ${quote(idxName)} ON ${qualifiedTable(e)} (${id(c.columnName)});"
    }

    private fun renderCompositeIndex(e: ExportEntity, cols: List<String>, unique: Boolean): String {
        val prefix = if (unique) "uq" else "idx"
        val raw = "${prefix}_${tableNameOf(e)}_${cols.joinToString("_")}".lowercase()
        val idxName = oracleLimit(raw)
        val colList = cols.joinToString(", ") { id(it) }
        val kw = if (unique) "CREATE UNIQUE INDEX" else "CREATE INDEX"
        return "$kw ${quote(idxName)} ON ${qualifiedTable(e)} ($colList);"
    }

    private fun renderFk(e: ExportEntity, c: ExportColumn, target: ExportEntity): String {
        val targetPks = target.columns.filter { it.primaryKey }
        val warn = if (targetPks.size > 1)
            "-- WARNING: target '${target.name}' has composite PK; FK references only first PK column.\n" else ""
        // 추출 범위 밖 대상이면 그 테이블은 이 스크립트에 없다 — 이미 존재한다고 가정함을 명시.
        val note = if (target.referenceOnly)
            "-- NOTE: referenced table '${tableNameOf(target)}' is outside this export; assumed to already exist.\n" else ""
        val targetPk = targetPks.firstOrNull()?.columnName ?: "id"
        return note + warn + fkAlterSql(
            qualifiedTable(e), id(c.columnName),
            qualifiedTable(target), id(targetPk),
            "fk_${tableNameOf(e)}_${c.columnName}"
        )
    }

    /**
     * `ALTER TABLE t ADD CONSTRAINT fk FOREIGN KEY (col) REFERENCES ref (refCol);` — FK 공통 형식.
     * 인자는 이미 quoting/스키마 한정된 식별자 표현. 제약명은 [fkBaseName] (스키마 미포함) 으로 생성.
     */
    private fun fkAlterSql(
        tableExpr: String, colExpr: String, refTableExpr: String, refColExpr: String, fkBaseName: String
    ): String {
        val fkName = oracleLimit(fkBaseName.lowercase())
        return "ALTER TABLE $tableExpr ADD CONSTRAINT ${quote(fkName)} " +
            "FOREIGN KEY ($colExpr) REFERENCES $refTableExpr ($refColExpr);"
    }

    // ===== ManyToMany 조인 테이블 =====
    /**
     * 조인 테이블의 물리 스펙 — owning @ManyToMany 관계 하나에서 도출.
     * 컬럼명은 JPA 기본 규칙 `{엔티티명}_{PK컬럼}` (예: student_id), 타입은 양쪽 PK 타입을 상속.
     */
    private data class JoinTableSpec(
        val name: String,
        val joinColumn: String, val joinColType: String, val ownerTable: String, val ownerPkCol: String,
        val inverseColumn: String, val inverseColType: String, val targetTable: String, val targetPkCol: String
    )

    private fun buildJoinTableSpec(r: ExportRelation, tableByFqn: Map<String, ExportEntity>): JoinTableSpec? {
        val owner = tableByFqn[r.source] ?: return null
        val target = tableByFqn[r.target] ?: return null
        val ownerPk = owner.columns.firstOrNull { it.primaryKey }
        val targetPk = target.columns.firstOrNull { it.primaryKey }
        val ownerPkCol = ownerPk?.columnName ?: "id"
        val targetPkCol = targetPk?.columnName ?: "id"
        return JoinTableSpec(
            name = r.joinTableName ?: "${tableNameOf(owner)}_${tableNameOf(target)}",
            // 커스텀 @JoinColumn 우선 — self-ref M:N(owner=target)은 기본 규칙이 같은 이름이라 커스텀 필수.
            joinColumn = r.joinColumnName ?: "${owner.name}_$ownerPkCol",
            joinColType = ownerPk?.let { sqlType(it) } ?: bigint(),
            ownerTable = tableNameOf(owner),
            ownerPkCol = ownerPkCol,
            inverseColumn = r.inverseJoinColumnName ?: "${target.name}_$targetPkCol",
            inverseColType = targetPk?.let { sqlType(it) } ?: bigint(),
            targetTable = tableNameOf(target),
            targetPkCol = targetPkCol
        )
    }

    private fun renderJoinTable(jt: JoinTableSpec): String = buildString {
        append("CREATE TABLE ").append(id(jt.name)).append(" (\n")
        append("    ").append(id(jt.joinColumn)).append(" ").append(jt.joinColType).append(" NOT NULL,\n")
        append("    ").append(id(jt.inverseColumn)).append(" ").append(jt.inverseColType).append(" NOT NULL,\n")
        append("    PRIMARY KEY (").append(id(jt.joinColumn)).append(", ").append(id(jt.inverseColumn)).append(")\n")
        append(");\n")
    }

    private fun renderJoinTableFks(jt: JoinTableSpec): String =
        fkAlterSql(id(jt.name), id(jt.joinColumn), id(jt.ownerTable), id(jt.ownerPkCol),
            "fk_${jt.name}_${jt.joinColumn}") + "\n" +
            fkAlterSql(id(jt.name), id(jt.inverseColumn), id(jt.targetTable), id(jt.targetPkCol),
                "fk_${jt.name}_${jt.inverseColumn}")

    // ===== 식별자 =====
    private fun tableNameOf(e: ExportEntity): String = e.tableName ?: e.name

    /** `@Table(schema=...)` 가 있으면 `"schema"."table"` 로 한정, 없으면 테이블 식별자만. */
    private fun qualifiedTable(e: ExportEntity): String {
        val table = id(tableNameOf(e))
        return e.schema?.let { "${id(it)}.$table" } ?: table
    }

    /** snake_case 변환 + 방언별 quoting 을 한 번에. */
    private fun id(name: String): String = quote(if (snakeCase) toSnakeCase(name) else name)

    private fun quote(name: String): String = when (dialect) {
        DdlDialect.MYSQL -> "`$name`"
        else -> "\"$name\""
    }

    /** UserAccount → user_account, userID → user_id, HTTPRequest → http_request. */
    private fun toSnakeCase(s: String): String {
        if (s.isEmpty()) return s
        val sb = StringBuilder(s.length + 4)
        for (i in s.indices) {
            val ch = s[i]
            if (i > 0 && ch.isUpperCase()) {
                val prev = s[i - 1]
                val next = s.getOrNull(i + 1)
                val isCamelBoundary = prev.isLowerCase() || prev.isDigit()
                val isAcronymBoundary = next != null && next.isLowerCase()
                if (isCamelBoundary || isAcronymBoundary) sb.append('_')
            }
            sb.append(ch.lowercaseChar())
        }
        return sb.toString()
    }

    /** Oracle 30 자 식별자 제한: 22 자 + '_' + 8 자 해시. 다른 방언엔 영향 없음. */
    private fun oracleLimit(name: String): String {
        if (dialect != DdlDialect.ORACLE || name.length <= 30) return name
        val hash = MessageDigest.getInstance("SHA-1").digest(name.toByteArray())
            .joinToString("") { "%02x".format(it) }.take(8)
        return name.take(21) + "_" + hash
    }

    // ===== 타입 매핑 =====
    private fun sqlType(c: ExportColumn): String {
        val simple = c.javaType.substringAfterLast('.')
        // @Lob 우선 처리 — length 무시하고 큰 텍스트/바이너리 타입으로.
        if (c.lob) return lobType(simple)
        // enum — javaType 은 enum FQN 이라 아래 when 으론 안 잡힘. ORDINAL→정수, STRING→VARCHAR.
        c.enumType?.let { return if (it.uppercase() == "ORDINAL") integer() else varchar(c.length ?: 255) }
        // @Temporal — java.util.Date/Calendar 의 DATE/TIME/TIMESTAMP 구분.
        c.temporalType?.let { return temporalSqlType(it) }
        return when (simple) {
            "String" -> varchar(c.length ?: 255)
            "Long", "long" -> bigint()
            "Integer", "int" -> integer()
            "Short", "short" -> smallint()
            "Byte", "byte" -> tinyint()
            "Boolean", "boolean" -> boolean()
            "Double", "double" -> doublePrecision()
            "Float", "float" -> realType()
            "BigDecimal" -> decimalType(c.precision ?: 19, c.scale ?: 2)
            "BigInteger" -> bigint()
            "LocalDate" -> "DATE"
            "LocalDateTime" -> when (dialect) {
                DdlDialect.MYSQL -> "DATETIME(6)"
                else -> "TIMESTAMP(6)"
            }
            "LocalTime" -> when (dialect) {
                DdlDialect.ORACLE -> "VARCHAR2(8)" // Oracle TIME 미지원 — 문자열 fallback
                else -> "TIME(6)"
            }
            "Instant", "OffsetDateTime", "ZonedDateTime" -> when (dialect) {
                DdlDialect.MYSQL -> "DATETIME(6)"
                DdlDialect.ORACLE, DdlDialect.POSTGRES -> "TIMESTAMP(6) WITH TIME ZONE"
                else -> "TIMESTAMP(6)"
            }
            "UUID" -> when (dialect) {
                DdlDialect.POSTGRES, DdlDialect.H2 -> "UUID"
                DdlDialect.MYSQL -> "CHAR(36)"
                DdlDialect.ORACLE -> "VARCHAR2(36)"
            }
            "byte[]", "Byte[]" -> when (dialect) {
                DdlDialect.POSTGRES -> "BYTEA"
                DdlDialect.MYSQL, DdlDialect.ORACLE -> "BLOB"
                DdlDialect.H2 -> "VARBINARY"
            }
            else -> varchar(c.length ?: 255) // enum / unknown → VARCHAR fallback
        }
    }

    /** @Temporal 종류 → SQL 타입. java.time.LocalDate/LocalTime/LocalDateTime 매핑과 동일 규칙. */
    private fun temporalSqlType(kind: String): String = when (kind.uppercase()) {
        "DATE" -> "DATE"
        "TIME" -> when (dialect) {
            DdlDialect.ORACLE -> "VARCHAR2(8)" // Oracle TIME 미지원 — 문자열 fallback
            else -> "TIME(6)"
        }
        else -> when (dialect) { // TIMESTAMP (기본)
            DdlDialect.MYSQL -> "DATETIME(6)"
            else -> "TIMESTAMP(6)"
        }
    }

    private fun lobType(simple: String): String {
        // byte[] / Byte[] 류 → BLOB. 그 외 (대개 String) → CLOB/TEXT.
        val binary = simple == "byte[]" || simple == "Byte[]"
        return when {
            binary && dialect == DdlDialect.POSTGRES -> "BYTEA"
            binary -> "BLOB"
            dialect == DdlDialect.POSTGRES -> "TEXT"
            dialect == DdlDialect.MYSQL -> "LONGTEXT"
            else -> "CLOB"
        }
    }

    private fun varchar(n: Int): String = when (dialect) {
        DdlDialect.ORACLE -> "VARCHAR2($n)"
        else -> "VARCHAR($n)"
    }

    private fun bigint(): String = when (dialect) {
        DdlDialect.ORACLE -> "NUMBER(19)"
        else -> "BIGINT"
    }

    private fun integer(): String = when (dialect) {
        DdlDialect.ORACLE -> "NUMBER(10)"
        else -> "INTEGER"
    }

    private fun smallint(): String = when (dialect) {
        DdlDialect.ORACLE -> "NUMBER(5)"
        else -> "SMALLINT"
    }

    private fun tinyint(): String = when (dialect) {
        DdlDialect.MYSQL -> "TINYINT"
        DdlDialect.ORACLE -> "NUMBER(3)"
        else -> "SMALLINT"
    }

    private fun boolean(): String = when (dialect) {
        DdlDialect.MYSQL -> "TINYINT(1)"
        DdlDialect.ORACLE -> "NUMBER(1)"
        else -> "BOOLEAN"
    }

    private fun doublePrecision(): String = when (dialect) {
        DdlDialect.POSTGRES -> "DOUBLE PRECISION"
        DdlDialect.ORACLE -> "BINARY_DOUBLE"
        else -> "DOUBLE"
    }

    private fun realType(): String = when (dialect) {
        DdlDialect.ORACLE -> "BINARY_FLOAT"
        else -> "REAL"
    }

    private fun decimalType(p: Int, s: Int): String = when (dialect) {
        DdlDialect.ORACLE -> "NUMBER($p, $s)"
        else -> "DECIMAL($p, $s)"
    }

    /** 정수형 PK 의 `@GeneratedValue` 를 방언 IDENTITY 절로. SEQUENCE 도 IDENTITY 로 fallback. */
    private fun identityClause(strategy: String): String? = when (strategy.uppercase()) {
        "IDENTITY", "AUTO", "SEQUENCE" -> when (dialect) {
            DdlDialect.POSTGRES, DdlDialect.H2, DdlDialect.ORACLE ->
                "GENERATED BY DEFAULT AS IDENTITY"
            DdlDialect.MYSQL -> "AUTO_INCREMENT"
        }
        else -> null
    }

    companion object {
        private val INTEGRAL_TYPES = setOf(
            "Long", "long", "Integer", "int", "Short", "short", "Byte", "byte", "BigInteger"
        )
        // SINGLE_TABLE 상속에서 @DiscriminatorColumn 이 명시되지 않았을 때의 JPA 기본값.
        private const val DEFAULT_DISCRIMINATOR_NAME = "DTYPE"
        private const val DEFAULT_DISCRIMINATOR_LENGTH = 31
    }
}
